language: node_js
node_js:
    - "8"

env:
  - TEST_DIR=client
  - TEST_DIR=server

cache:
  directories:
    - client/node_modules
    - server/node_modules

install: cd $TEST_DIR && npm install
script: cd $TEST_DIR && npm run build && npm test
