sudo: false

language: node_js

node_js:
  - '10'
  - '12'

env:
  - TEST_DIR=client
  - TEST_DIR=server

cache:
  directories:
    - $TEST_DIR/node_modules

before_install:
  - cd $TEST_DIR

install:
  - npm install

script:
  - npm run build
  - npm test
